#!/bin/bash -e
# ref. https://sue445.hatenablog.com/entry/2019/03/02/220617

if [ -n "$1" ]; then
  master=$1
else
  master=$(git remote show origin | grep 'HEAD branch:' | cut -d : -f 2 | tr -d '[[:space:]]')
fi

current=$(git symbolic-ref --short HEAD)

git checkout "$master"
git pull origin "$master"
git checkout "$current"
git rebase "$master"
